@startuml

title __PERF's Class Diagram__\n

  package  {
    package testsuite {
      package testsuite.perf {
        abstract class BasePerfTest {
            {static} - T95 : double[]
            {static} - T99 : double[]
            {static} ~ numberFormatter : NumberFormat
            - testValuesList : List<Double>
            - confidenceLevel : double
            - confidenceValue : double
            - intervalWidth : double
            - meanValue : double
            - squareSumValue : double
            - sumValue : double
            - variationValue : double
            - numIterations : int
            + BasePerfTest()
            + getMeanValue()
            {abstract} # doOneIteration()
            # getCurrentConfidence()
            # getMarginOfError()
            # getStandardDeviationP()
            # addResult()
            # doIterations()
            # reportResults()
            - getConfidenceLookup()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.perf {
        class LoadStorePerfTest {
            - tableType : String
            - takeMeasurements : boolean
            - useColumnNames : boolean
            - largeResults : boolean
            + LoadStorePerfTest()
            {static} + main()
            + setUp()
            + tearDown()
            + test1000Transactions()
            # doOneIteration()
            # warmUp()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.perf {
        class RetrievalPerfTest {
            {static} - NUM_TESTS : int
            {static} - NUM_ROWS : int
            + RetrievalPerfTest()
            {static} + main()
            + setUp()
            + testRetrievalCached()
            + testRetrievalHeap()
            + testRetrievalMyIsam()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
