@startuml

title __NONBLOCKING's Class Diagram__\n

  package  {
    package nonblocking {
      class ByteCounter {
          {static} - serialVersionUID : long
          # doGet()
          # doPost()
      }
    }
  }
  

  package  {
    package nonblocking {
      class CounterListener {
          - ac : AsyncContext
          - sis : ServletInputStream
          - sos : ServletOutputStream
          - readFinished : boolean
          - totalBytesRead : long
          - buffer : byte[]
          - CounterListener()
          + onDataAvailable()
          + onAllDataRead()
          + onWritePossible()
          + onError()
      }
    }
  }
  

  package  {
    package nonblocking {
      class ByteCounter {
          {static} - serialVersionUID : long
          + ByteCounter()
          # doGet()
          # doPost()
      }
    }
  }
  

  package  {
    package nonblocking {
      class CounterListener {
          - ac : AsyncContext
          - sis : ServletInputStream
          - sos : ServletOutputStream
          - readFinished : boolean
          - totalBytesRead : long
          - buffer : byte[]
          - CounterListener()
          + onDataAvailable()
          + onAllDataRead()
          + onWritePossible()
          + onError()
      }
    }
  }
  

  package  {
    package nonblocking {
      class NumberWriter {
          {static} - serialVersionUID : long
          # doGet()
      }
    }
  }
  

  package  {
    package nonblocking {
      class NumberWriterListener {
          {static} - LIMIT : int
          - ac : AsyncContext
          - sis : ServletInputStream
          - sos : ServletOutputStream
          - counter : AtomicInteger
          - readFinished : boolean
          - buffer : byte[]
          - NumberWriterListener()
          + onDataAvailable()
          + onAllDataRead()
          + onWritePossible()
          + onError()
      }
    }
  }
  

  package  {
    package nonblocking {
      class NumberWriter {
          {static} - serialVersionUID : long
          + NumberWriter()
          # doGet()
      }
    }
  }
  

  package  {
    package nonblocking {
      class NumberWriterListener {
          {static} - LIMIT : int
          - ac : AsyncContext
          - sis : ServletInputStream
          - sos : ServletOutputStream
          - counter : AtomicInteger
          - readFinished : boolean
          - buffer : byte[]
          - NumberWriterListener()
          + onDataAvailable()
          + onAllDataRead()
          + onWritePossible()
          + onError()
      }
    }
  }
  

  ByteCounter +-down- CounterListener
  CounterListener -up-|> ReadListener
  CounterListener -up-|> WriteListener
  ByteCounter -up-|> HttpServlet
  ByteCounter +-down- CounterListener
  CounterListener -up-|> ReadListener
  CounterListener -up-|> WriteListener
  NumberWriter +-down- NumberWriterListener
  NumberWriterListener -up-|> ReadListener
  NumberWriterListener -up-|> WriteListener
  NumberWriter -up-|> HttpServlet
  NumberWriter +-down- NumberWriterListener
  NumberWriterListener -up-|> ReadListener
  NumberWriterListener -up-|> WriteListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
