@startuml

title __FABRIC's Class Diagram__\n

  package  {
    package testsuite {
      package testsuite.fabric {
        abstract class BaseFabricTestCase {
            # hostname : String
            # portString : String
            # fabricUsername : String
            # fabricPassword : String
            # username : String
            # password : String
            # database : String
            # globalHost : String
            # globalPort : String
            # shard1Host : String
            # shard1Port : String
            # shard2Host : String
            # shard2Port : String
            # port : int
            # fabricUrl : String
            # baseJdbcUrl : String
            # isSetForFabricTest : boolean
            + BaseFabricTestCase()
            # getNewDefaultDataSource()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class SetupFabricTestsuite {
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestAdminCommands {
            - client : XmlRpcClient
            + TestAdminCommands()
            + setUp()
            + testCreateGroup()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestDumpCommands {
            - client : XmlRpcClient
            {static} + serverHostnamePortSorter : Comparator<Server>
            + TestDumpCommands()
            + setUp()
            + testDumpServersAll()
            + testDumpShardMapsAll()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestResultSetParser {
            ~ exampleServersResultSet : List<Map<String, ?>>
            + TestResultSetParser()
            + setUp()
            + testExampleData()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestShardMapping {
            + testRangeShardMappingKeyLookup()
            + testHashShardMappingKeyLookup()
            + testBug82203()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestBug82203RunnableMock {
            {static} - run : boolean
            - time : long
            + TestBug82203RunnableMock()
            + run()
            - makeKey()
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        class TestXmlRpcCore {
            + TestXmlRpcCore()
            + generateAuthHeaders()
            + testProtocol()
        }
      }
    }
  }
  

  TestShardMapping +-down- TestBug82203RunnableMock
  TestBug82203RunnableMock -up-|> Runnable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
