@startuml

title __JMX's Class Diagram__\n

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.jmx {
        class LoadBalanceConnectionGroupManager {
            - isJmxRegistered : boolean
            + LoadBalanceConnectionGroupManager()
            + registerJmx()
            + addHost()
            + getActiveHostCount()
            + getActiveLogicalConnectionCount()
            + getActivePhysicalConnectionCount()
            + getTotalHostCount()
            + getTotalLogicalConnectionCount()
            + getTotalPhysicalConnectionCount()
            + getTotalTransactionCount()
            + removeHost()
            + getActiveHostsList()
            + getRegisteredConnectionGroups()
            + stopNewConnectionsToHost()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.jmx {
        interface LoadBalanceConnectionGroupManagerMBean {
            {abstract} + getActiveHostCount()
            {abstract} + getTotalHostCount()
            {abstract} + getTotalLogicalConnectionCount()
            {abstract} + getActiveLogicalConnectionCount()
            {abstract} + getActivePhysicalConnectionCount()
            {abstract} + getTotalPhysicalConnectionCount()
            {abstract} + getTotalTransactionCount()
            {abstract} + removeHost()
            {abstract} + stopNewConnectionsToHost()
            {abstract} + addHost()
            {abstract} + getActiveHostsList()
            {abstract} + getRegisteredConnectionGroups()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.jmx {
        class ReplicationGroupManager {
            - isJmxRegistered : boolean
            + registerJmx()
            + addSlaveHost()
            + removeSlaveHost()
            + promoteSlaveToMaster()
            + removeMasterHost()
            + getMasterHostsList()
            + getSlaveHostsList()
            + getRegisteredConnectionGroups()
            + getActiveMasterHostCount()
            + getActiveSlaveHostCount()
            + getSlavePromotionCount()
            + getTotalLogicalConnectionCount()
            + getActiveLogicalConnectionCount()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.jmx {
        interface ReplicationGroupManagerMBean {
            {abstract} + addSlaveHost()
            {abstract} + removeSlaveHost()
            {abstract} + promoteSlaveToMaster()
            {abstract} + removeMasterHost()
            {abstract} + getMasterHostsList()
            {abstract} + getSlaveHostsList()
            {abstract} + getRegisteredConnectionGroups()
            {abstract} + getActiveMasterHostCount()
            {abstract} + getActiveSlaveHostCount()
            {abstract} + getSlavePromotionCount()
            {abstract} + getTotalLogicalConnectionCount()
            {abstract} + getActiveLogicalConnectionCount()
        }
      }
    }
  }
  

  LoadBalanceConnectionGroupManager -up-|> LoadBalanceConnectionGroupManagerMBean
  ReplicationGroupManager -up-|> ReplicationGroupManagerMBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
