@startuml

title __UTIL's Class Diagram__\n

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class Base64Decoder {
            {static} - decoderMap : byte[]
            {static} - getNextValidByte()
            {static} + decode()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class IntWrapper {
            + value : int
            + IntWrapper()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        abstract class BaseBugReport {
            - conn : Connection
            - driver : Driver
            + BaseBugReport()
            {abstract} + setUp()
            {abstract} + tearDown()
            {abstract} + runTest()
            + run()
            # assertTrue()
            # assertTrue()
            + getUrl()
            + getConnection()
            + getNewConnection()
            + getConnection()
            + getConnection()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class ErrorMappingsDocGenerator {
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class LRUCache {
            {static} - serialVersionUID : long
            # maxElements : int
            + LRUCache()
            # removeEldestEntry()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class PropertiesDocGenerator {
            {static} ~ serialVersionUID : long
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class ReadAheadInputStream {
            {static} - DEFAULT_BUFFER_SIZE : int
            - underlyingStream : InputStream
            - buf : byte[]
            # endOfCurrentData : int
            # currentPosition : int
            # doDebug : boolean
            # log : Log
            - fill()
            - readFromUnderlyingStreamIfNecessary()
            + read()
            + read()
            + available()
            - checkClosed()
            + ReadAheadInputStream()
            + ReadAheadInputStream()
            + close()
            + markSupported()
            + skip()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class ResultSetUtil {
            {static} + appendResultSetSlashGStyle()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class ServerController {
            {static} + BASEDIR_KEY : String
            {static} + DATADIR_KEY : String
            {static} + DEFAULTS_FILE_KEY : String
            {static} + EXECUTABLE_NAME_KEY : String
            {static} + EXECUTABLE_PATH_KEY : String
            - serverProcess : Process
            - serverProps : Properties
            - systemProps : Properties
            + ServerController()
            + ServerController()
            + setBaseDir()
            + setDataDir()
            + start()
            + stop()
            + forceStop()
            + getServerProps()
            - getCommandLine()
            - getFullExecutablePath()
            - buildOptionalCommandLine()
            - isNonCommandLineArgument()
            - getSystemProperties()
            - runningOnWindows()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class TimezoneDump {
            {static} - DEFAULT_URL : String
            + TimezoneDump()
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.util {
        class VersionFSHierarchyMaker {
            {static} + main()
            {static} + removeWhitespaceChars()
            {static} - usage()
        }
      }
    }
  }
  

  Base64Decoder +-down- IntWrapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
