@startuml

title __JDBC42's Class Diagram__\n

  package  {
    package testsuite {
      package testsuite.simple {
        package testsuite.simple.jdbc4 {
          package testsuite.simple.jdbc42 {
            class ConnectionTest {
                + ConnectionTest()
                + testDriverAcceptsURLNullArgument()
                + testDriverConnectNullArgument()
                + testDriverConnectPropertiesPrecedence()
                + testSupportsRefCursors()
            }
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.simple {
        package testsuite.simple.jdbc4 {
          package testsuite.simple.jdbc42 {
            class ResultSetTest {
                + ResultSetTest()
                + testNonUpdResultSetUpdateObject()
                + testUpdResultSetUpdateObjectAndNewSupportedTypes()
                + testUpdResultSetUpdateObjectAndNewUnsupportedTypes()
            }
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.simple {
        package testsuite.simple.jdbc4 {
          package testsuite.simple.jdbc42 {
            class StatementsTest {
                - testDateString : String
                - testTimeString : String
                - testDateTimeString : String
                - testISODateTimeString : String
                - testSqlDate : Date
                - testSqlTime : Time
                - testSqlTimeStamp : Timestamp
                - testLocalDate : LocalDate
                - testLocalTime : LocalTime
                - testLocalDateTime : LocalDateTime
                - testOffsetDateTime : OffsetDateTime
                - testOffsetTime : OffsetTime
                + StatementsTest()
                + testSharedTestData()
                + testStmtExecuteLargeBatch()
                + testStmtExecuteLargeUpdateNoGeneratedKeys()
                + testStmtExecuteLargeUpdate()
                + testPrepStmtExecuteLargeBatch()
                + testPrepStmtExecuteLargeUpdateNoGeneratedKeys()
                + testPrepStmtExecuteLargeUpdateExplicitGeneratedKeys()
                + testCallStmtExecuteLargeBatch()
                + testCallStmtExecuteLargeUpdate()
                + testServerPrepStmtExecuteLargeBatch()
                + testStmtGetSetLargeMaxRows()
                + testPrepStmtSetObjectAndNewSupportedTypes()
                + testPrepStmtSetObjectAndNewUnsupportedTypes()
                + testCallStmtSetObjectAndNewSupportedTypes()
                + testCallStmtSetObjectAndNewUnsupportedTypes()
                + testServPrepStmtSetObjectAndNewSupportedTypes()
                + testServPrepStmtSetObjectAndNewUnsupportedTypes()
                - insertTestDataLocalDTTypes()
                - validateTestDataLocalDTTypes()
                - insertTestDataOffsetDTTypes()
                - validateTestDataOffsetDTTypes()
                - checkUnsupportedTypesBehavior()
                + testCallStmtRegisterOutParameter()
                + testCallStmtRegisterOutParameterNewUnsupportedTypes()
            }
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
