@startuml

title __SIMPLETAG's Class Diagram__\n

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class EchoAttributesTag {
            - keys : List<String>
            - values : List<Object>
            + doTag()
            + setDynamicAttribute()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class EchoAttributesTag {
            - keys : List<String>
            - values : List<Object>
            + EchoAttributesTag()
            + doTag()
            + setDynamicAttribute()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class FindBookSimpleTag {
            - var : String
            {static} - BOOK_TITLE : String
            {static} - BOOK_AUTHOR : String
            {static} - BOOK_ISBN : String
            + doTag()
            + setVar()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class FindBookSimpleTag {
            - var : String
            {static} - BOOK_TITLE : String
            {static} - BOOK_AUTHOR : String
            {static} - BOOK_ISBN : String
            + FindBookSimpleTag()
            + doTag()
            + setVar()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class HelloWorldSimpleTag {
            + HelloWorldSimpleTag()
            + doTag()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class HelloWorldSimpleTag {
            + doTag()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class RepeatSimpleTag {
            - num : int
            + doTag()
            + setNum()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class RepeatSimpleTag {
            - num : int
            + RepeatSimpleTag()
            + doTag()
            + setNum()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class ShuffleSimpleTag {
            {static} - random : Random
            - fragment1 : JspFragment
            - fragment2 : JspFragment
            - fragment3 : JspFragment
            + ShuffleSimpleTag()
            + doTag()
            + setFragment1()
            + setFragment2()
            + setFragment3()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class ShuffleSimpleTag {
            {static} - random : Random
            - fragment1 : JspFragment
            - fragment2 : JspFragment
            - fragment3 : JspFragment
            + doTag()
            + setFragment1()
            + setFragment2()
            + setFragment3()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class TileSimpleTag {
            - color : String
            - label : String
            + doTag()
            + setColor()
            + setLabel()
        }
      }
    }
  }
  

  package  {
    package jsp2.examples {
      package jsp2.examples.simpletag {
        class TileSimpleTag {
            - color : String
            - label : String
            + TileSimpleTag()
            + doTag()
            + setColor()
            + setLabel()
        }
      }
    }
  }
  

  EchoAttributesTag -up-|> DynamicAttributes
  EchoAttributesTag -up-|> DynamicAttributes
  EchoAttributesTag -up-|> SimpleTagSupport
  FindBookSimpleTag -up-|> SimpleTagSupport
  HelloWorldSimpleTag -up-|> SimpleTagSupport
  RepeatSimpleTag -up-|> SimpleTagSupport
  ShuffleSimpleTag -up-|> SimpleTagSupport
  TileSimpleTag -up-|> SimpleTagSupport


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
