@startuml

title __JDBC's Class Diagram__\n

  package  {
    package testsuite {
      package testsuite.fabric {
        package testsuite.fabric.jdbc {
          class TestBasicConnection {
              + TestBasicConnection()
              + testConnectionUrl()
              + testConnectionDataSource()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        package testsuite.fabric.jdbc {
          class TestFabricMySQLConnectionSharding {
              - ds : FabricMySQLDataSource
              - conn : FabricMySQLConnection
              + TestFabricMySQLConnectionSharding()
              + setUp()
              + tearDown()
              + testGlobalTableCreation()
              + testShardSelection()
              + testQueryTableShardSelection()
              + testQueryTablesPreventCrossShardQuery()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        package testsuite.fabric.jdbc {
          class TestHABasics {
              - ds : FabricMySQLDataSource
              - conn : FabricMySQLConnection
              - masterPort : String
              + TestHABasics()
              + setUp()
              + tearDown()
              - getPort()
              + testReadWriteSplitting()
              + manualTestFailover()
              + manualTestNewConnHasNewState()
              + manualTestFailedOldMasterDoesntBlockNewConnections()
              + manualTestFailedSingleSlaveDoesntBlockNewConnections()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        package testsuite.fabric.jdbc {
          class TestHashSharding {
              - ds : FabricMySQLDataSource
              - conn : FabricMySQLConnection
              + TestHashSharding()
              + setUp()
              + tearDown()
              # checkRowExists()
              # checkRowDoesntExist()
              # checkRowExistsInServerGroup()
              # checkRowExistsInKeyGroup()
              # checkRowDoesntExistInServerGroup()
              + checkRowDoesntExistInKeyGroup()
              # assertBasicDataIsInProperPlaces()
              + testBasicInsertByGroup()
              + testBasicInsertByKey()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.fabric {
        package testsuite.fabric.jdbc {
          class TestRegressions {
              - conn : FabricMySQLConnection
              + TestRegressions()
              + testBug73070()
              + testBug75080()
              + testBug77217()
              + testBug21876798()
              + manualTestRefreshFabricStateCache()
              + testBug82094()
              + manualTestBug22750465()
              - manualTestBug22750465SomeReadWriteOperations()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
