@startuml

title __PROFILER's Class Diagram__\n

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.profiler {
        class LoggingProfilerEventHandler {
            - log : Log
            + LoggingProfilerEventHandler()
            + consumeEvent()
            + destroy()
            + init()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.profiler {
        class ProfilerEvent {
            {static} + TYPE_WARN : byte
            {static} + TYPE_OBJECT_CREATION : byte
            {static} + TYPE_PREPARE : byte
            {static} + TYPE_QUERY : byte
            {static} + TYPE_EXECUTE : byte
            {static} + TYPE_FETCH : byte
            {static} + TYPE_SLOW_QUERY : byte
            # eventType : byte
            # connectionId : long
            # statementId : int
            # resultSetId : int
            # eventCreationTime : long
            # eventDuration : long
            # durationUnits : String
            # hostNameIndex : int
            # hostName : String
            # catalogIndex : int
            # catalog : String
            # eventCreationPointIndex : int
            # eventCreationPointDesc : String
            # message : String
            + ProfilerEvent()
            + getEventCreationPointAsString()
            + toString()
            {static} + unpack()
            + pack()
            {static} - writeInt()
            {static} - writeLong()
            {static} - writeBytes()
            {static} - readInt()
            {static} - readLong()
            {static} - readBytes()
            + getCatalog()
            + getConnectionId()
            + getEventCreationTime()
            + getEventDuration()
            + getDurationUnits()
            + getEventType()
            + getResultSetId()
            + getStatementId()
            + getMessage()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.profiler {
        interface ProfilerEventHandler {
            {abstract} + consumeEvent()
        }
      }
    }
  }
  

  LoggingProfilerEventHandler -up-|> ProfilerEventHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
