@startuml

title __LISTENERS's Class Diagram__\n

  package  {
    package listeners {
      class ContextListener {
          - context : ServletContext
          + ContextListener()
          + attributeAdded()
          + attributeRemoved()
          + attributeReplaced()
          + contextDestroyed()
          + contextInitialized()
          - log()
      }
    }
  }
  

  package  {
    package listeners {
      class ContextListener {
          - context : ServletContext
          + attributeAdded()
          + attributeRemoved()
          + attributeReplaced()
          + contextDestroyed()
          + contextInitialized()
          - log()
      }
    }
  }
  

  package  {
    package listeners {
      class SessionListener {
          - context : ServletContext
          + SessionListener()
          + attributeAdded()
          + attributeRemoved()
          + attributeReplaced()
          + contextDestroyed()
          + contextInitialized()
          + sessionCreated()
          + sessionDestroyed()
          - log()
      }
    }
  }
  

  package  {
    package listeners {
      class SessionListener {
          - context : ServletContext
          + attributeAdded()
          + attributeRemoved()
          + attributeReplaced()
          + contextDestroyed()
          + contextInitialized()
          + sessionCreated()
          + sessionDestroyed()
          - log()
      }
    }
  }
  

  ContextListener -up-|> ServletContextAttributeListener
  ContextListener -up-|> ServletContextListener
  ContextListener -up-|> ServletContextAttributeListener
  ContextListener -up-|> ServletContextListener
  SessionListener -up-|> ServletContextListener
  SessionListener -up-|> HttpSessionAttributeListener
  SessionListener -up-|> HttpSessionListener
  SessionListener -up-|> ServletContextListener
  SessionListener -up-|> HttpSessionAttributeListener
  SessionListener -up-|> HttpSessionListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
