@startuml

title __EXAMPLES's Class Diagram__\n

  package  {
    package examples {
      abstract class ExampleTagBase {
          {static} - serialVersionUID : long
          # bodyOut : BodyContent
          # parent : Tag
          + ExampleTagBase()
          + setParent()
          + setBodyContent()
          + getParent()
          + doStartTag()
          + doEndTag()
          + doInitBody()
          + doAfterBody()
          + release()
      }
    }
  }
  

  package  {
    package examples {
      abstract class ExampleTagBase {
          {static} - serialVersionUID : long
          # bodyOut : BodyContent
          # parent : Tag
          + setParent()
          + setBodyContent()
          + getParent()
          + doStartTag()
          + doEndTag()
          + doInitBody()
          + doAfterBody()
          + release()
      }
    }
  }
  

  package  {
    package examples {
      class FooTag {
          {static} - serialVersionUID : long
          - atts : String[]
          ~ i : int
          + FooTag()
          - setAtt()
          + setAtt1()
          + setAtt2()
          + setAtt3()
          + doStartTag()
          + doInitBody()
          + doAfterBody()
      }
    }
  }
  

  package  {
    package examples {
      class FooTag {
          {static} - serialVersionUID : long
          - atts : String[]
          ~ i : int
          - setAtt()
          + setAtt1()
          + setAtt2()
          + setAtt3()
          + doStartTag()
          + doInitBody()
          + doAfterBody()
      }
    }
  }
  

  package  {
    package examples {
      class FooTagExtraInfo {
          + getVariableInfo()
      }
    }
  }
  

  package  {
    package examples {
      class FooTagExtraInfo {
          + FooTagExtraInfo()
          + getVariableInfo()
      }
    }
  }
  

  package  {
    package examples {
      class LogTag {
          {static} - serialVersionUID : long
          ~ toBrowser : boolean
          + LogTag()
          + setToBrowser()
          + doStartTag()
          + doAfterBody()
      }
    }
  }
  

  package  {
    package examples {
      class LogTag {
          {static} - serialVersionUID : long
          ~ toBrowser : boolean
          + setToBrowser()
          + doStartTag()
          + doAfterBody()
      }
    }
  }
  

  package  {
    package examples {
      class ShowSource {
          {static} - serialVersionUID : long
          ~ jspFile : String
          + ShowSource()
          + setJspFile()
          + doEndTag()
      }
    }
  }
  

  package  {
    package examples {
      class ShowSource {
          {static} - serialVersionUID : long
          ~ jspFile : String
          + setJspFile()
          + doEndTag()
      }
    }
  }
  

  package  {
    package examples {
      class ValuesTag {
          {static} - serialVersionUID : long
          - objectValue : Object
          - stringValue : String
          - longValue : long
          - doubleValue : double
          + ValuesTag()
          + setObject()
          + setString()
          + setLong()
          + setDouble()
          + doEndTag()
      }
    }
  }
  

  package  {
    package examples {
      class ValuesTag {
          {static} - serialVersionUID : long
          - objectValue : Object
          - stringValue : String
          - longValue : long
          - doubleValue : double
          + setObject()
          + setString()
          + setLong()
          + setDouble()
          + doEndTag()
      }
    }
  }
  

  ExampleTagBase -up-|> BodyTagSupport
  FooTagExtraInfo -up-|> TagExtraInfo
  ShowSource -up-|> TagSupport
  ValuesTag -up-|> TagSupport


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
