@startuml

title __CAL's Class Diagram__\n

  package  {
    package cal {
      class Entries {
          - entries : Hashtable<String, Entry>
          {static} - time : String[]
          {static} + rows : int
          + Entries()
          + getRows()
          + getEntry()
          + getIndex()
          + processRequest()
      }
    }
  }
  

  package  {
    package cal {
      class Entries {
          - entries : Hashtable<String, Entry>
          {static} - time : String[]
          {static} + rows : int
          + Entries()
          + getRows()
          + getEntry()
          + getIndex()
          + processRequest()
      }
    }
  }
  

  package  {
    package cal {
      class Entry {
          ~ hour : String
          ~ description : String
          + Entry()
          + getHour()
          + getColor()
          + getDescription()
          + setDescription()
      }
    }
  }
  

  package  {
    package cal {
      class Entry {
          ~ hour : String
          ~ description : String
          + Entry()
          + getHour()
          + getColor()
          + getDescription()
          + setDescription()
      }
    }
  }
  

  package  {
    package cal {
      class JspCalendar {
          ~ calendar : Calendar
          + JspCalendar()
          + getYear()
          + getMonth()
          + getDay()
          + getMonthInt()
          + getDate()
          + getCurrentDate()
          + getNextDate()
          + getPrevDate()
          + getTime()
          + getDayOfMonth()
          + getDayOfYear()
          + getWeekOfYear()
          + getWeekOfMonth()
          + getDayOfWeek()
          + getHour()
          + getMinute()
          + getSecond()
          + getEra()
          + getUSTimeZone()
          + getZoneOffset()
          + getDSTOffset()
          + getAMPM()
      }
    }
  }
  

  package  {
    package cal {
      class JspCalendar {
          ~ calendar : Calendar
          + JspCalendar()
          + getYear()
          + getMonth()
          + getDay()
          + getMonthInt()
          + getDate()
          + getCurrentDate()
          + getNextDate()
          + getPrevDate()
          + getTime()
          + getDayOfMonth()
          + getDayOfYear()
          + getWeekOfYear()
          + getWeekOfMonth()
          + getDayOfWeek()
          + getHour()
          + getMinute()
          + getSecond()
          + getEra()
          + getUSTimeZone()
          + getZoneOffset()
          + getDSTOffset()
          + getAMPM()
      }
    }
  }
  

  package  {
    package cal {
      class TableBean {
          ~ table : Hashtable<String, Entries>
          ~ JspCal : JspCalendar
          ~ entries : Entries
          ~ date : String
          ~ name : String
          ~ email : String
          ~ processError : boolean
          + TableBean()
          + setName()
          + getName()
          + setEmail()
          + getEmail()
          + getDate()
          + getEntries()
          + processRequest()
          + getProcessError()
      }
    }
  }
  

  package  {
    package cal {
      class TableBean {
          ~ table : Hashtable<String, Entries>
          ~ JspCal : JspCalendar
          ~ entries : Entries
          ~ date : String
          ~ name : String
          ~ email : String
          ~ processError : boolean
          + TableBean()
          + setName()
          + getName()
          + setEmail()
          + getEmail()
          + getDate()
          + getEntries()
          + processRequest()
          + getProcessError()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
