@startuml

title __JDBC4's Class Diagram__\n

  package  {
    package testsuite {
      package testsuite.regression {
        package testsuite.regression.jdbc4 {
          class ConnectionRegressionTest {
              + ConnectionRegressionTest()
              {static} + main()
              + testBug75168()
              + testBug20685022()
              + testBug62452()
              - testBug62452WithConnection()
              + testBug16634180()
              + testBug56122()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.regression {
        package testsuite.regression.jdbc4 {
          class ExceptionSubclassesTest {
              + ExceptionSubclassesTest()
              + testBug17750877()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.regression {
        package testsuite.regression.jdbc4 {
          class MetaDataRegressionTest {
              + MetaDataRegressionTest()
              {static} + main()
              + testBug68307()
              - checkFunctionColumnTypeForBug68307()
              - checkProcedureColumnTypeForBug68307()
              + testBug44451()
              - checkReturnedColumnsForBug44451()
              + testBug69298()
              - checkGetFunctionsForBug69298()
              - checkGetFunctionColumnsForBug69298()
              - checkGetProceduresForBug69298()
              - checkGetProcedureColumnsForBug69298()
              + testBug17248345()
              - checkMetaDataInfoForBug17248345()
              + testReservedWords()
              + testBug20504139()
              + testBug19803348()
              + testBug20727196()
              + testBug73775()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.regression {
        package testsuite.regression.jdbc4 {
          class StatementRegressionTest {
              + StatementRegressionTest()
              {static} + main()
              + testBug68916()
              - subTestBug68916ForStandardConnection()
              - subTestBug68916ForHoldResultsOpenOverStatementClose()
              - subTestBug68916ForDontTrackOpenResources()
              - subTestBug68916ForAllowMultiQueries()
              - subTestBug68916ForConcurrency()
              + testBug73163()
              + testBug78313()
          }
        }
      }
    }
  }
  

  package  {
    package testsuite {
      package testsuite.regression {
        package testsuite.regression.jdbc4 {
          class subTestBug68916ConcurrentTask {
              ~ testConnection : Connection
              ~ query : String
              ~ closeOnCompletionIsOverriden : boolean
              ~ subTestBug68916ConcurrentTask()
              + call()
          }
        }
      }
    }
  }
  

  StatementRegressionTest +-down- subTestBug68916ConcurrentTask
  subTestBug68916ConcurrentTask -up-|> Callable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
