@startuml

title __AUTHENTICATION's Class Diagram__\n

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        class CachingSha2PasswordPlugin {
            {static} + PLUGIN_NAME : String
            + init()
            + destroy()
            + getProtocolPluginName()
            + nextAuthenticationStep()
            # encryptPassword()
            + reset()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        enum AuthStage {
          FAST_AUTH_SEND_SCRAMBLE
          FAST_AUTH_READ_RESULT
          FAST_AUTH_COMPLETE
          FULL_AUTH
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        class MysqlClearPasswordPlugin {
            - connection : Connection
            - password : String
            + init()
            + destroy()
            + getProtocolPluginName()
            + requiresConfidentiality()
            + isReusable()
            + setAuthenticationParameters()
            + nextAuthenticationStep()
            + reset()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        class MysqlNativePasswordPlugin {
            - connection : Connection
            - password : String
            + init()
            + destroy()
            + getProtocolPluginName()
            + requiresConfidentiality()
            + isReusable()
            + setAuthenticationParameters()
            + nextAuthenticationStep()
            + reset()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        class MysqlOldPasswordPlugin {
            - connection : Connection
            - password : String
            + init()
            + destroy()
            + getProtocolPluginName()
            + requiresConfidentiality()
            + isReusable()
            + setAuthenticationParameters()
            + nextAuthenticationStep()
            + reset()
        }
      }
    }
  }
  

  package  {
    package com.mysql.jdbc {
      package com.mysql.jdbc.authentication {
        class Sha256PasswordPlugin {
            {static} + PLUGIN_NAME : String
            # connection : Connection
            # password : String
            # seed : String
            # publicKeyRequested : boolean
            # publicKeyString : String
            + init()
            + destroy()
            + getProtocolPluginName()
            + requiresConfidentiality()
            + isReusable()
            + setAuthenticationParameters()
            + nextAuthenticationStep()
            # encryptPassword()
            # encryptPassword()
            {static} - readRSAKey()
            + reset()
        }
      }
    }
  }
  

  CachingSha2PasswordPlugin o-- AuthStage : stage
  CachingSha2PasswordPlugin +-down- AuthStage
  MysqlClearPasswordPlugin -up-|> AuthenticationPlugin
  MysqlNativePasswordPlugin -up-|> AuthenticationPlugin
  MysqlOldPasswordPlugin -up-|> AuthenticationPlugin
  Sha256PasswordPlugin -up-|> AuthenticationPlugin


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
